services:
  blogApp:
    build:
      context: ..  # Specifies the build context (parent directory)
      dockerfile: .devcontainer/Dockerfile  # Path to the Dockerfile in the .devcontainer directory
    container_name: stunning-braccoli-strapi
    image: stunning-braccoli-strapi
    volumes:
      - stunning-braccoli-volume-strapi:/workspace  # Mounts the volume to /workspace
    ports:
      - "1337:1337"  # Maps port 3001
volumes:
  stunning-braccoli-volume-strapi:  # Defines the volume
